In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
dataset = pd.read_csv('C:/Users/ravee/Jupyter/Skin-Cancer-Classification/data/data.csv', header=None)
X = dataset.iloc[:, 0:55].values
Y = dataset.iloc[:, 56].values

In [3]:
# Important information about the data used in this model
# 0 - 5    : Color attributes (Mean, Std Dev)
# 6 - 31   : LBP attributes (Texture #1)
# 32 - 55  : GLCM attributes (Texture #2)

# 56 : Identifier

# 1 = Melanoma
# 2 = Basal Cell Carcinoma
# 3 = Squamous Cell Carcinoma

dataset

0           1           2          3          4          5   \
0    169.256450  202.590651  242.497507  54.823602  51.052070  26.222353   
1    108.462145  153.931848  212.770833  47.916776  50.114792  32.598578   
2    210.075311  220.092924  253.834964  34.058778  27.562333   2.447045   
3    166.967572  174.194743  225.132927  44.874775  46.330424  35.535939   
4    147.359097  157.010846  185.615266  64.245087  62.478155  54.582425   
..          ...         ...         ...        ...        ...        ...   
677  216.271625  207.522922  254.092376  35.953658  28.445054   1.980630   
678  201.302389  213.250941  253.622319  27.262874  20.897481   9.089076   
679  198.379915  196.230370  252.047819  29.067900  22.506142   5.481164   
680  132.429821  149.086324  248.498059  45.724390  34.462111  11.402881   
681  230.667314  221.230961  254.115972  28.389489  28.544260   1.575036   

           6         7         8         9   ...        47        48  \
0    0.000083  0.000155  0.000059  0.000143  ...  0.685561  0.986359   
1    0.000000  0.000122  0.000027  0.000231  ...  0.680274  0.980717   
2    0.000000  0.000057  0.000000  0.000172  ...  0.726408  0.970713   
3    0.000292  0.000504  0.000319  0.001566  ...  0.651558  0.975344   
4    0.000000  0.000102  0.000102  0.000409  ...  0.670741  0.977183   
..        ...       ...       ...       ...  ...       ...       ...   
677  0.000559  0.000838  0.000424  0.000694  ...  0.699715  0.974411   
678  0.000018  0.000229  0.000132  0.000494  ...  0.778285  0.979561   
679  0.000551  0.000767  0.000340  0.000594  ...  0.684338  0.983161   
680  0.000000  0.000071  0.000028  0.000227  ...  0.721304  0.982767   
681  0.000962  0.000789  0.000271  0.000668  ...  0.691695  0.974998   

           49        50        51        52        53        54        55  56  
0    0.979975  0.984579  0.978706  0.472019  0.470765  0.471009  0.469994   1  
1    0.967215  0.976585  0.973490  0.464470  0.460822  0.461779  0.462773   1  
2    0.955162  0.969559  0.966326  0.520789  0.524100  0.520656  0.527669   1  
3    0.957002  0.965519  0.960409  0.425697  0.422765  0.420703  0.424528   1  
4    0.967147  0.977047  0.969475  0.451838  0.449249  0.451438  0.449893   1  
..        ...       ...       ...       ...       ...       ...       ...  ..  
677  0.962479  0.974294  0.964876  0.492014  0.488870  0.491274  0.489601   3  
678  0.969742  0.980869  0.975053  0.607069  0.603949  0.607634  0.605727   3  
679  0.972880  0.980382  0.976323  0.468929  0.467087  0.467613  0.468319   3  
680  0.972922  0.979823  0.973809  0.523331  0.520013  0.521998  0.520279   3  
681  0.965423  0.976717  0.966234  0.480442  0.478231  0.480729  0.478441   3  

[682 rows x 57 columns]

In [99]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [100]:
len(X_train)

545

In [101]:
len(X_test)

137

In [102]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Support Vector Machine (SVM)

In [57]:
# Implementation of Support Vector Machine (SVM)
# Fitting SVM to the training set

from sklearn.svm import SVC
classifier = SVC(C = 1, kernel = 'rbf', random_state = 0)
#classifier = SVC(C = 1, kernel = 'poly', degree = 30, random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [58]:
# Predicting the test set result
y_pred = classifier.predict(X_test)

# Making the confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm2 = multilabel_confusion_matrix(y_test, y_pred)

cm

array([[47,  7,  3],
       [ 8, 37,  4],
       [ 9, 13,  9]], dtype=int64)

In [59]:
# Calculating the accuracy and other metrics

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

target_names = ['melanoma', 'bcc', 'scc']

acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=target_names)

print(report)

              precision    recall  f1-score   support

    melanoma       0.73      0.82      0.78        57
         bcc       0.65      0.76      0.70        49
         scc       0.56      0.29      0.38        31

    accuracy                           0.68       137
   macro avg       0.65      0.62      0.62       137
weighted avg       0.66      0.68      0.66       137



# Artificial Neural Network (ANN)

In [12]:
# Importing the Keras libraries and packages
import keras
import sys
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

Using TensorFlow backend.


In [14]:
# Create categorical input for predictor

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(handle_unknown='ignore')
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)
y_binary = onehotencoder.fit_transform(y_train).toarray()
y_compare = onehotencoder.fit_transform(y_test).toarray()

In [147]:
# Initializing the ANN
classifier = Sequential()

# Adding the input & hidden layer
classifier.add(Dense(32, activation = 'relu', input_shape = (55,)))
classifier.add(Dense(32, activation = 'relu'))
classifier.add(Dense(32, activation = 'relu'))
classifier.add(Dense(3, activation = 'softmax'))
classifier.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

classifier.fit(X_train, y_binary, batch_size = 10, epochs = 100)

Epoch 1/100
545/545 [==============================] - 0s 283us/step - loss: 1.0079 - accuracy: 0.5009
Epoch 2/100
545/545 [==============================] - 0s 126us/step - loss: 0.8874 - accuracy: 0.5835
Epoch 3/100
545/545 [==============================] - 0s 117us/step - loss: 0.8361 - accuracy: 0.5982
Epoch 4/100
545/545 [==============================] - 0s 110us/step - loss: 0.7909 - accuracy: 0.6275
Epoch 5/100
545/545 [==============================] - 0s 111us/step - loss: 0.7410 - accuracy: 0.6569
Epoch 6/100
545/545 [==============================] - 0s 111us/step - loss: 0.6880 - accuracy: 0.6789
Epoch 7/100
545/545 [==============================] - 0s 118us/step - loss: 0.6531 - accuracy: 0.7009
Epoch 8/100
545/545 [==============================] - 0s 117us/step - loss: 0.6057 - accuracy: 0.7321
Epoch 9/100
545/545 [==============================] - 0s 110us/step - loss: 0.5749 - accuracy: 0.7413
Epoch 10/100
545/545 [==============================] - 0s 117us/step - l

545/545 [==============================] - 0s 114us/step - loss: 0.0117 - accuracy: 1.0000
Epoch 80/100
545/545 [==============================] - 0s 120us/step - loss: 0.0107 - accuracy: 1.0000
Epoch 81/100
545/545 [==============================] - 0s 103us/step - loss: 0.0130 - accuracy: 1.0000
Epoch 82/100
545/545 [==============================] - 0s 110us/step - loss: 0.0165 - accuracy: 0.9982
Epoch 83/100
545/545 [==============================] - 0s 110us/step - loss: 0.0106 - accuracy: 1.0000
Epoch 84/100
545/545 [==============================] - 0s 103us/step - loss: 0.0094 - accuracy: 1.0000
Epoch 85/100
545/545 [==============================] - 0s 103us/step - loss: 0.0083 - accuracy: 1.0000
Epoch 86/100
545/545 [==============================] - 0s 110us/step - loss: 0.0082 - accuracy: 1.0000
Epoch 87/100
545/545 [==============================] - 0s 103us/step - loss: 0.0073 - accuracy: 1.0000
Epoch 88/100
545/545 [==============================] - 0s 110us/step - loss:

In [148]:
# Create threshold for multi-predictor
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [149]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

cm = confusion_matrix(y_compare.argmax(axis=1), y_pred.argmax(axis=1))

cm

array([[46,  6,  5],
       [11, 29,  9],
       [ 9, 10, 12]], dtype=int64)

In [150]:
# Calculating the accuracy and other metrics

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

target_names = ['melanoma', 'bcc', 'scc']

acc = accuracy_score(y_compare.argmax(axis=1), y_pred.argmax(axis=1))
report = classification_report(y_compare.argmax(axis=1), y_pred.argmax(axis=1), target_names=target_names)

print(report)

              precision    recall  f1-score   support

    melanoma       0.70      0.81      0.75        57
         bcc       0.64      0.59      0.62        49
         scc       0.46      0.39      0.42        31

    accuracy                           0.64       137
   macro avg       0.60      0.60      0.60       137
weighted avg       0.62      0.64      0.63       137



# Decision Trees

In [112]:
# Some important notes here, before running the Decision Tree Classifier, it's ok to not scale the features, as this model
# does not work using euclidian distance, so it's fine as it is

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 1000)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=1000, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [113]:
# Predicting the test set result
y_pred = classifier.predict(X_test)

# Making the confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm2 = multilabel_confusion_matrix(y_test, y_pred)

cm

array([[46,  6,  5],
       [ 8, 27, 14],
       [ 5, 12, 14]], dtype=int64)

In [114]:
# Calculating the accuracy and other metrics

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

target_names = ['melanoma', 'bcc', 'scc']

acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=target_names)

print(report)

              precision    recall  f1-score   support

    melanoma       0.78      0.81      0.79        57
         bcc       0.60      0.55      0.57        49
         scc       0.42      0.45      0.44        31

    accuracy                           0.64       137
   macro avg       0.60      0.60      0.60       137
weighted avg       0.63      0.64      0.63       137



# Random Forest (Ensemble)

In [144]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0, verbose = 1)
classifier.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1000 out of 1000 | elapsed:    3.7s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=1,
                       warm_start=False)

In [145]:
# Predicting the test set result
y_pred = classifier.predict(X_test)

# Making the confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm2 = multilabel_confusion_matrix(y_test, y_pred)

cm

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1000 out of 1000 | elapsed:    0.0s finished


array([[49,  6,  2],
       [10, 34,  5],
       [12, 10,  9]], dtype=int64)

In [146]:
# Calculating the accuracy and other metrics

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

target_names = ['melanoma', 'bcc', 'scc']

acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=target_names)

print(report)

              precision    recall  f1-score   support

    melanoma       0.69      0.86      0.77        57
         bcc       0.68      0.69      0.69        49
         scc       0.56      0.29      0.38        31

    accuracy                           0.67       137
   macro avg       0.64      0.61      0.61       137
weighted avg       0.66      0.67      0.65       137

